export const fallbackCalendarKeywordTemplates = [
  "{subject}",
  "what is {subject}",
  "how does {subject} work",
  "best {subject} options",
  "{subject} for beginners",
  "{subject} examples",
  "{subject} benefits",
  "{subject} drawbacks",
  "{subject} alternatives",
  "{subject} comparison",
  "{subject} cost",
  "is {subject} worth it",
  "how to choose {subject}",
  "how to start with {subject}",
  "how to use {subject}",
  "common {subject} mistakes",
  "{subject} questions",
  "{subject} features",
  "{subject} reviews",
  "{subject} tips",
  "{subject} problems",
  "{subject} solutions",
  "{subject} use cases",
  "{subject} explained",
  "{subject} step by step",
  "{subject} best practices",
  "{subject} beginner questions",
  "{subject} pros and cons",
  "{subject} vs manual methods",
  "when to use {subject}",
  "who should use {subject}",
  "what to look for in {subject}",
  "how to compare {subject}",
  "free {subject} options",
  "affordable {subject} options",
  "{subject} for personal goals",
  "{subject} for everyday use",
  "{subject} without complicated tools",
  "getting started with {subject}",
  "choosing the right {subject}",
  "why use {subject}",
  "do you need {subject}",
  "{subject} questions and answers",
  "{subject} misconceptions",
  "{subject} safety questions",
  "{subject} privacy questions",
  "{subject} hidden costs",
  "{subject} warning signs",
  "{subject} results to expect",
  "{subject} success stories",
  "{subject} myths and facts",
  "{subject} first steps",
  "{subject} everyday challenges",
  "{subject} decision questions",
  "{subject} beginner mistakes",
  "{subject} practical examples",
  "{subject} simple strategies",
  "{subject} ways to improve",
  "{subject} common concerns",
  "{subject} important considerations",
] as const;
