import type { TopicExpansionPattern } from "./types/TopicExpansionPattern";

export const topicExpansionPatterns: TopicExpansionPattern[] = [
  {
    intent: "Help readers choose with clear buying criteria.",
    notes: "Cover the must-have checks before someone chooses a tool or process.",
    sourceType: "discovery",
    template: "{base} buying decision checklist criteria for {scope}",
  },
  {
    intent: "Help readers get started without guessing.",
    notes: "Turn the topic into a practical first setup plan.",
    sourceType: "discovery",
    template: "{base} setup launch checklist steps for {scope}",
  },
  {
    intent: "Help readers avoid problems before they start.",
    notes: "Frame the article around mistakes, warning signs, and fixes.",
    sourceType: "gap",
    template: "{base} workflow mistakes warning signs for {scope}",
  },
  {
    intent: "Help readers compare options before making a decision.",
    notes: "Make the comparison practical and focused on real tradeoffs.",
    sourceType: "comparison",
    template: "{base} comparison questions tradeoffs checklist for {scope}",
  },
  {
    intent: "Help readers decide when an alternative makes sense.",
    notes: "Compare options in plain language and explain who each one fits.",
    sourceType: "comparison",
    template: "{base} alternatives pros cons matrix for {scope}",
  },
  {
    intent: "Answer pricing questions before readers commit.",
    notes: "Explain what affects cost and what readers should check first.",
    sourceType: "question",
    template: "{base} pricing budget questions checklist for {scope}",
  },
  {
    intent: "Help readers onboard with less confusion.",
    notes: "Show the first week of steps, decisions, and small wins.",
    sourceType: "discovery",
    template: "{base} onboarding first week plan for {scope}",
  },
  {
    intent: "Help readers move from idea to working process.",
    notes: "Break implementation into simple decisions and repeatable steps.",
    sourceType: "discovery",
    template: "{base} implementation roadmap milestones for {scope}",
  },
  {
    intent: "Help readers make a confident decision.",
    notes: "Give readers a short list of criteria they can apply immediately.",
    sourceType: "discovery",
    template: "{base} decision framework scorecard for {scope}",
  },
  {
    intent: "Help readers understand the value they should expect.",
    notes: "Tie the article to useful outcomes, not vague benefits.",
    sourceType: "question",
    template: "{base} ROI measurement metrics guide for {scope}",
  },
  {
    intent: "Help readers clean up a messy process.",
    notes: "Focus on practical fixes for scattered or slow work.",
    sourceType: "gap",
    template: "{base} process cleanup workflow audit for {scope}",
  },
  {
    intent: "Help readers solve common problems.",
    notes: "List symptoms, likely causes, and the simplest fixes.",
    sourceType: "question",
    template: "{base} troubleshooting common problems fixes for {scope}",
  },
  {
    intent: "Help readers track what matters.",
    notes: "Show the numbers, signs, and review habits worth watching.",
    sourceType: "discovery",
    template: "{base} reporting metrics dashboard for {scope}",
  },
  {
    intent: "Help readers check whether a solution has what they need.",
    notes: "Turn features into reader-friendly buying and setup checks.",
    sourceType: "discovery",
    template: "{base} feature checklist requirements for {scope}",
  },
  {
    intent: "Help readers see practical ways to use the topic.",
    notes: "Use examples that make the article concrete and easy to scan.",
    sourceType: "discovery",
    template: "{base} use case examples playbook for {scope}",
  },
  {
    intent: "Help readers run a repeatable review.",
    notes: "Give readers a reusable template they can follow.",
    sourceType: "gap",
    template: "{base} weekly review template questions for {scope}",
  },
  {
    intent: "Help readers know what to ask before they buy.",
    notes: "Turn the topic into a practical list of buyer questions.",
    sourceType: "question",
    template: "{base} buyer questions vendor evaluation for {scope}",
  },
  {
    intent: "Help readers plan a smooth switch.",
    notes: "Cover what to prepare, move, test, and check after launch.",
    sourceType: "discovery",
    template: "{base} migration plan spreadsheet replacement for {scope}",
  },
  {
    intent: "Help readers train a team without overcomplicating it.",
    notes: "Show a plain training plan with roles, steps, and review points.",
    sourceType: "discovery",
    template: "{base} team training rollout plan for {scope}",
  },
  {
    intent: "Help readers decide what to do first.",
    notes: "Prioritize the small actions that create early progress.",
    sourceType: "discovery",
    template: "{base} quick wins priority list for {scope}",
  },
  {
    intent: "Help readers spot gaps in their current setup.",
    notes: "Use a self-audit format with clear next steps.",
    sourceType: "gap",
    template: "{base} self audit checklist gaps for {scope}",
  },
  {
    intent: "Help readers choose between doing it manually or using a tool.",
    notes: "Explain when manual work still fits and when it starts costing too much.",
    sourceType: "comparison",
    template: "{base} manual process tool comparison for {scope}",
  },
  {
    intent: "Help readers understand what good looks like.",
    notes: "Give practical quality markers and examples.",
    sourceType: "question",
    template: "{base} best practice standards examples for {scope}",
  },
  {
    intent: "Help readers plan around common objections.",
    notes: "Address worries, blockers, and easy ways to move forward.",
    sourceType: "question",
    template: "{base} objections concerns answers for {scope}",
  },
  {
    intent: "Help readers map a complete workflow.",
    notes: "Show the before, during, and after steps in one simple flow.",
    sourceType: "discovery",
    template: "{base} end to end workflow map for {scope}",
  },
  {
    intent: "Help readers build a simple checklist.",
    notes: "Keep the article focused on actions readers can complete.",
    sourceType: "discovery",
    template: "{base} step by step checklist for {scope}",
  },
  {
    intent: "Help readers compare free and paid choices.",
    notes: "Explain tradeoffs in plain language and avoid hype.",
    sourceType: "comparison",
    template: "{base} free paid options comparison for {scope}",
  },
  {
    intent: "Help readers understand what to automate.",
    notes: "Separate work that should stay human from repeatable tasks.",
    sourceType: "gap",
    template: "{base} automation opportunities task audit for {scope}",
  },
  {
    intent: "Help readers plan a simple launch.",
    notes: "Show what to prepare before, during, and after launch.",
    sourceType: "discovery",
    template: "{base} launch plan timeline for {scope}",
  },
  {
    intent: "Help readers choose the right starting point.",
    notes: "Make the article useful for someone who feels stuck or overloaded.",
    sourceType: "question",
    template: "{base} where to start roadmap for {scope}",
  },
  {
    intent: "Help readers reduce wasted time.",
    notes: "Connect the topic to bottlenecks, delays, and simple fixes.",
    sourceType: "gap",
    template: "{base} time saving bottleneck fixes for {scope}",
  },
  {
    intent: "Help readers improve adoption.",
    notes: "Focus on behavior, buy-in, and simple habits that make the process stick.",
    sourceType: "gap",
    template: "{base} adoption habits change plan for {scope}",
  },
  {
    intent: "Help readers explain the value to someone else.",
    notes: "Give readers a clear way to make the case internally.",
    sourceType: "discovery",
    template: "{base} business case talking points for {scope}",
  },
  {
    intent: "Help readers avoid buying the wrong thing.",
    notes: "Show mismatch signs, hidden costs, and questions to ask.",
    sourceType: "comparison",
    template: "{base} wrong choice red flags for {scope}",
  },
  {
    intent: "Help readers improve a current setup.",
    notes: "Focus on better habits, clearer rules, and small upgrades.",
    sourceType: "refresh",
    template: "{base} current setup improvement ideas for {scope}",
  },
  {
    intent: "Help readers prepare for growth.",
    notes: "Explain what breaks as volume grows and how to plan ahead.",
    sourceType: "gap",
    template: "{base} scaling plan growing workload for {scope}",
  },
  {
    intent: "Help readers answer common search questions directly.",
    notes: "Use clear headings and direct answers for each question.",
    sourceType: "question",
    template: "{base} frequently asked questions answers for {scope}",
  },
  {
    intent: "Help readers compare real workflows.",
    notes: "Use side-by-side examples that make tradeoffs easy to understand.",
    sourceType: "comparison",
    template: "{base} workflow comparison examples for {scope}",
  },
  {
    intent: "Help readers create a simple operating routine.",
    notes: "Show the recurring checks and habits that keep the process useful.",
    sourceType: "discovery",
    template: "{base} operating routine checklist for {scope}",
  },
  {
    intent: "Help readers understand what to stop doing.",
    notes: "Make the article about removing busywork and unclear steps.",
    sourceType: "gap",
    template: "{base} busywork cleanup stop doing for {scope}",
  },
  {
    intent: "Help readers judge quality before committing.",
    notes: "Give signs of a solid option and signs to be careful.",
    sourceType: "comparison",
    template: "{base} quality signals evaluation checklist for {scope}",
  },
  {
    intent: "Help readers plan content around the product niche.",
    notes: "Connect the article to customer questions and buying intent.",
    sourceType: "discovery",
    template: "{base} customer education content ideas for {scope}",
  },
  {
    intent: "Help readers make a simple plan for the next month.",
    notes: "Break the work into weekly steps and useful checkpoints.",
    sourceType: "discovery",
    template: "{base} thirty day action plan for {scope}",
  },
  {
    intent: "Help readers decide whether now is the right time.",
    notes: "Explain timing signals, readiness, and what to do next.",
    sourceType: "question",
    template: "{base} readiness signs timing checklist for {scope}",
  },
  {
    intent: "Help readers compare beginner and advanced needs.",
    notes: "Separate simple needs from features that only matter later.",
    sourceType: "comparison",
    template: "{base} beginner advanced needs comparison for {scope}",
  },
  {
    intent: "Help readers turn research into a decision.",
    notes: "Organize the article around notes, shortlist steps, and final checks.",
    sourceType: "discovery",
    template: "{base} research shortlist decision process for {scope}",
  },
  {
    intent: "Help readers use the product niche in a real scenario.",
    notes: "Make the article concrete with a realistic scenario and takeaway.",
    sourceType: "discovery",
    template: "{base} real world scenario walkthrough for {scope}",
  },
  {
    intent: "Help readers recover when a process is not working.",
    notes: "Cover diagnosis, quick fixes, and prevention.",
    sourceType: "gap",
    template: "{base} failed process recovery plan for {scope}",
  },
];
